format = """
[╭─](bold #A3BE8C)$username$directory$git_branch$git_status$cmd_duration
[╰─](bold #A3BE8C)$character"""

[username]
style_user = "bold #A3BE8C"
style_root = "bold red"
format = "[$user]($style) in "
show_always = true
disabled = false

[directory]
style = "bold #eeeeee"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "#A3BE8C"
format = "on [$symbol$branch]($style) "

[git_status]
style = "red"
format = "[$all_status$ahead_behind]($style) "

[cmd_duration]
min_time = 500
style = "dimmed #eeeeee"
format = "took [$duration]($style) "

[character]
success_symbol = "[❯](bold #A3BE8C)"
error_symbol = "[❯](bold red)"
