[colors]
background = #B8000000
foreground = #eeeeee
blue   = #A3BE8C
green  = #A3BE8C
red    = #d35f5e
purple = #989cff
orange = #d19a66

[bar/top]
monitor = ${env:MONITOR:}
width = 100%
height = 28
fixed-center = true
line-size = 2
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 0
padding-left = 1
padding-right = 1
module-margin = 1
;wm-restack = i3


tray-position = right
tray-detached = false
tray-maxsize = 14
tray-padding = 2
tray-scale = 1.0


modules-left = filesystem i3
modules-center = temperature memory cpu
modules-right = alsa xkeyboard time network powermenu

font-0 = "JetBrainsMono Nerd Font:style=Bold:pixelsize=11;3"
font-1 = "JetBrainsMono Nerd Font:size=14;4"
font-2 = "Material Design Icons:style=Bold:size=11;3"

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
label-focused = %index%
label-focused-foreground = #ffffff
label-focused-background = #2b2f37
label-focused-underline = ${colors.blue}
label-focused-padding = 2
label-unfocused = %index%
label-unfocused-padding = 2
label-urgent = %index%
label-urgent-background = ${colors.red}
label-urgent-padding = 2

[module/alsa]
type = internal/alsa
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
ramp-volume-0 = %{F#d35f5e}󰖀 %{F-}
ramp-volume-1 = %{F#d35f5e}󰕾 %{F-}
format-muted-foreground = ${colors.red}
label-muted = 󰖁 Muted

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format-prefix = "  "
format-prefix-foreground = ${colors.blue}
label-layout = %layout%

[module/network]
type = internal/network
interface-type = wired
format-connected-prefix = "󰈀 "
format-connected-prefix-foreground = ${colors.green}
label-connected = " Online"

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.orange}
label = %gb_used%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.purple}
label = %percentage%%

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 70
format = <ramp> <label>
label = %temperature-c%
ramp-0 = "%{F#a4ebf3} %{F-}"

[module/time]
type = internal/date
interval = 1
date = %{F#888e96} %H:%M%{F-}
date-alt = %{F#A3BE8C} %a, %d %b %Y%{F-}
label = %date%

[module/filesystem]
type = custom/text 
content =" " 
content-foreground = ${colors.blue}
click-left = rofi -show drun

[module/powermenu]
type = custom/text 
content =" " 
content-foreground = ${colors.red}
click-left = i3-msg exit
