[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true

; Активный рабочий стол (Цветной)
label-focused = %index%
label-focused-foreground = #ffffff
label-focused-background = #2b2f37
label-focused-underline = #61afef
label-focused-padding = 2

; Неактивные
label-unfocused = %index%
label-unfocused-foreground = #646870
label-unfocused-padding = 2

[module/alsa]
type = internal/alsa
; Иконка звука будет розово-красной
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
ramp-volume-0 = %{F#d35f5e}󰖀 %{F-}
ramp-volume-1 = %{F#d35f5e}󰕾 %{F-}
format-muted-foreground = #d35f5e
label-muted = 󰖁 muted

[module/memory]
type = internal/memory
; Иконка памяти — оранжевая
format-prefix = " "
format-prefix-foreground = #d19a66
label = %gb_used%

[module/cpu]
type = internal/cpu
; Иконка процессора — фиолетовая
format-prefix = " "
format-prefix-foreground = #989cff
label = %percentage%%

[module/xkeyboard]
type = internal/xkeyboard
; Иконка клавиатуры — голубая
format-prefix = "  "
format-prefix-foreground = #61afef
label-layout = %layout%

[module/network]
type = internal/network
interface-type = wired
; Иконка сети — зеленая
format-connected-prefix = "󰈀 "
format-connected-prefix-foreground = #A3BE8C
label-connected = " Online"
