font_family      JetBrainsMono Nerd Font
font_size        12.0
disable_ligatures never
bold_font        auto
italic_font      auto
bold_italic_font auto

background       #000000
foreground       #eeeeee

cursor           #A3BE8C
cursor_shape     beam
cursor_beam_thickness 1.8
cursor_trail     3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 1

selection_background #A3BE8C
selection_foreground #000000

color4           #A3BE8C
color12          #A3BE8C

window_padding_width 12
background_opacity 0.72
background_blur 32
dynamic_background_opacity yes

active_border_color   #A3BE8C
inactive_border_color #2b2f37

# Tab bar
tab_bar_edge          top
tab_bar_style          powerline
tab_powerline_style    slanted
tab_bar_min_tabs       2
tab_title_template     " {title} "
active_tab_foreground   #000000
active_tab_background   #A3BE8C
active_tab_font_style   bold
inactive_tab_foreground #888888
inactive_tab_background #1a1a1a

confirm_os_window_close 0

# Disable audio bell
enable_audio_bell no
